### ISSUE TITLE
The tag cannot be used for the simulator

### ISSUE THREAD

**Issue by shiguanglindi** [AirAmaz/AirAmaz-Sector#3]
When i start a simulator of tower,the defualt crews's squawk are setted at S mode.So,i can't get the control permissions to control the crews.

**Comment by Misaka-Nnnnq** [comment]
Thanks for your feedback.

I will fix it in the next update cycle.
For now you can set ``General Settings`` --> ``Professional mode`` --> ``Correlation mode`` to ``Easy`` manually.
